//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreyOTron.Library.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GreyOTronResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GreyOTronResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreyOTron.Library.Translations.GreyOTronResources", typeof(GreyOTronResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GW2API did not return worlds for user {0}.
        /// </summary>
        internal static string ApiFailedToReturnWorldsForUser {
            get {
                return ResourceManager.GetString("ApiFailedToReturnWorldsForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GW2API did not return worlds for you..
        /// </summary>
        internal static string ApiFailedToReturnWorldsForYou {
            get {
                return ResourceManager.GetString("ApiFailedToReturnWorldsForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tried using &apos;{0}&apos;, unfortunately I haven&apos;t been taught that command..
        /// </summary>
        internal static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version: {0}.
        /// </summary>
        internal static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure your GW2 application key&apos;s name is the same as your discord username: {0}#{1}.
        /// </summary>
        internal static string DiscordNameDifferentFromGw2Key {
            get {
                return ResourceManager.GetString("DiscordNameDifferentFromGw2Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This key seems empty to me, please try again..
        /// </summary>
        internal static string EmptyKeyTryAgain {
            get {
                return ResourceManager.GetString("EmptyKeyTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view, create and edit your GW2 application key&apos;s on https://account.arena.net/applications.
        /// </summary>
        internal static string FindYourGW2ApplicationKey {
            get {
                return ResourceManager.GetString("FindYourGW2ApplicationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GW2 api can&apos;t handle this request at the time, please try again a bit later..
        /// </summary>
        internal static string GW2ApiUnableToProcess {
            get {
                return ResourceManager.GetString("GW2ApiUnableToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help can be found on https://greyotron.eu
        ///{0} Or find help on https://discord.gg/6uybq5X.
        /// </summary>
        internal static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your api-key is invalid, please set a new one and re-verify..
        /// </summary>
        internal static string InvalidApiKey {
            get {
                return ResourceManager.GetString("InvalidApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} api-key is invalid, please set a new one and re-verify..
        /// </summary>
        internal static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No key found for {0}.
        /// </summary>
        internal static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t yet registered a key with me, use the gw2-key command to do so..
        /// </summary>
        internal static string KeyNotRegistered {
            get {
                return ResourceManager.GetString("KeyNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} set for {1} as main world..
        /// </summary>
        internal static string MainWorldSet {
            get {
                return ResourceManager.GetString("MainWorldSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seems to be an issue with the role &apos;{0}&apos; on &apos;{1}&apos; it&apos;s most likely above the &apos;Grey-O-Tron&apos; role making it impossible for the bot the assign it..
        /// </summary>
        internal static string NotGuildUserRoleIssue {
            get {
                return ResourceManager.GetString("NotGuildUserRoleIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give at least one world name separated by ; for the set-worlds command to work..
        /// </summary>
        internal static string NoWorldsInCommand {
            get {
                return ResourceManager.GetString("NoWorldsInCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong whilst trying to assign you the &apos;{0}&apos; role on &apos;{1}&apos;, the bot owner is notified, please  try again in 60 minutes..
        /// </summary>
        internal static string RoleAssignmentFailed {
            get {
                return ResourceManager.GetString("RoleAssignmentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong whilst trying to assign &apos;{0}&apos; the &apos;{1}&apos; role on &apos;{2}&apos;, the bot owner is notified please try again in 60 minutes..
        /// </summary>
        internal static string RoleAssignmentFailedForUser {
            get {
                return ResourceManager.GetString("RoleAssignmentFailedForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your gw2 world roles have been removed from {0}.
        ///Goodbye!.
        /// </summary>
        internal static string RolesWereRemoved {
            get {
                return ResourceManager.GetString("RolesWereRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no where.
        /// </summary>
        internal static string RolesWereRemovedNoWhere {
            get {
                return ResourceManager.GetString("RolesWereRemovedNoWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your key has been stored, and we also tried to verify you on the following Discord servers:
        ///{0}.
        /// </summary>
        internal static string SuccessfullyVerified {
            get {
                return ResourceManager.GetString("SuccessfullyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The set-worlds command must be used from within the server to which you want to apply it..
        /// </summary>
        internal static string TriedSetWorldsWhilstNotOnServer {
            get {
                return ResourceManager.GetString("TriedSetWorldsWhilstNotOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must use the gw2-verify command from within the discord server you try to get verified on..
        /// </summary>
        internal static string TriedVerifyWhilstNotOnServer {
            get {
                return ResourceManager.GetString("TriedVerifyWhilstNotOnServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry you&apos;re not authorized to receive this kind of information..
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have administrative permissions to perform the set-worlds command..
        /// </summary>
        internal static string UnauthorizedToSetWorlds {
            get {
                return ResourceManager.GetString("UnauthorizedToSetWorlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve your world from &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownWorld {
            get {
                return ResourceManager.GetString("UnknownWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; already had the role &apos;{1}&apos; on &apos;{2}&apos;, no action taken..
        /// </summary>
        internal static string UserAlreadyHadRole {
            get {
                return ResourceManager.GetString("UserAlreadyHadRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} most likely changed their discord username from {1} to {2}#{3} please ask {0} to update their key.\n{4}.
        /// </summary>
        internal static string UserChangedDiscordUsername {
            get {
                return ResourceManager.GetString("UserChangedDiscordUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been assigned {1} on {2}.
        /// </summary>
        internal static string UserHasBeenAssignedRole {
            get {
                return ResourceManager.GetString("UserHasBeenAssignedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an issue on the &apos;{0}&apos; for the role &apos;{1}&apos; an administrator from the server is notified..
        /// </summary>
        internal static string UserMessageForRoleIssue {
            get {
                return ResourceManager.GetString("UserMessageForRoleIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User you are trying to verify was not found on this Discord server..
        /// </summary>
        internal static string UserNotFoundForVerification {
            get {
                return ResourceManager.GetString("UserNotFoundForVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s world is not in &apos;{1}&apos; worlds list, cannot assign the role {2}.
        /// </summary>
        internal static string WorldNotInDiscordServerWorlds {
            get {
                return ResourceManager.GetString("WorldNotInDiscordServerWorlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} set for {1}.
        /// </summary>
        internal static string WorldsSetForGuild {
            get {
                return ResourceManager.GetString("WorldsSetForGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the role &apos;{0}&apos; on &apos;{1}&apos;, nothing changed..
        /// </summary>
        internal static string YouAlreadyHadRole {
            get {
                return ResourceManager.GetString("YouAlreadyHadRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve most likely changed your discord username from {0} to {1}#{2}, please update your key.\n{3}.
        /// </summary>
        internal static string YouChangedDiscordUsername {
            get {
                return ResourceManager.GetString("YouChangedDiscordUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been assigned {0} on {1}.
        /// </summary>
        internal static string YouHaveBeenAssignedRole {
            get {
                return ResourceManager.GetString("YouHaveBeenAssignedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your world &apos;{0}&apos; is not in this server&apos;s &apos;{1}&apos; worlds list..
        /// </summary>
        internal static string YourWorldNotInDiscordServerWorlds {
            get {
                return ResourceManager.GetString("YourWorldNotInDiscordServerWorlds", resourceCulture);
            }
        }
    }
}
