//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreyOTron.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GreyOTronResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GreyOTronResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreyOTron.Resources.GreyOTronResources", typeof(GreyOTronResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have administrative permissions to perform the {0} command..
        /// </summary>
        public static string AdministrativePermissionsOnly {
            get {
                return ResourceManager.GetString("AdministrativePermissionsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0} to &apos;{1}&apos;
        ///I noticed you already have a GW2 api key registered with me and I will now attempt to verify you in this server..
        /// </summary>
        public static string AlreadyHasGw2KeyRegisteredAutoVerifyOnJoin {
            get {
                return ResourceManager.GetString("AlreadyHasGw2KeyRegisteredAutoVerifyOnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GW2API did not return worlds for user {0}.
        /// </summary>
        public static string ApiFailedToReturnWorldsForUser {
            get {
                return ResourceManager.GetString("ApiFailedToReturnWorldsForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GW2API did not return worlds for you..
        /// </summary>
        public static string ApiFailedToReturnWorldsForYou {
            get {
                return ResourceManager.GetString("ApiFailedToReturnWorldsForYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You tried using &apos;{0}&apos;, unfortunately I haven&apos;t been taught that command..
        /// </summary>
        public static string CommandNotFound {
            get {
                return ResourceManager.GetString("CommandNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version: {0}.
        /// </summary>
        public static string CurrentVersion {
            get {
                return ResourceManager.GetString("CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please make sure your GW2 application key&apos;s name is the same as your discord username: {0}#{1}.
        /// </summary>
        public static string DiscordNameDifferentFromGw2Key {
            get {
                return ResourceManager.GetString("DiscordNameDifferentFromGw2Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This key seems empty to me, please try again..
        /// </summary>
        public static string EmptyKeyTryAgain {
            get {
                return ResourceManager.GetString("EmptyKeyTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view, create and edit your GW2 application key&apos;s on https://account.arena.net/applications.
        /// </summary>
        public static string FindYourGW2ApplicationKey {
            get {
                return ResourceManager.GetString("FindYourGW2ApplicationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GW2 api can&apos;t handle this request at the time, please try again a bit later..
        /// </summary>
        public static string GW2ApiUnableToProcess {
            get {
                return ResourceManager.GetString("GW2ApiUnableToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help can be found on https://greyotron.eu
        ///{0} Or find help on https://discord.gg/6uybq5X.
        /// </summary>
        public static string HelpMessage {
            get {
                return ResourceManager.GetString("HelpMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your api-key is invalid, please set a new one and re-verify..
        /// </summary>
        public static string InvalidApiKey {
            get {
                return ResourceManager.GetString("InvalidApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} api-key is invalid, please set a new one and re-verify..
        /// </summary>
        public static string InvalidKey {
            get {
                return ResourceManager.GetString("InvalidKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The language &apos;{0}&apos; you tried setting isn&apos;t valid..
        /// </summary>
        public static string InvalidLanguage {
            get {
                return ResourceManager.GetString("InvalidLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No key found for {0}.
        /// </summary>
        public static string KeyNotFound {
            get {
                return ResourceManager.GetString("KeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t yet registered a key with me, use the gw2-key command to do so..
        /// </summary>
        public static string KeyNotRegistered {
            get {
                return ResourceManager.GetString("KeyNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language &apos;{0}&apos; is now set as the preferred language for {1}..
        /// </summary>
        public static string LanguageSet {
            get {
                return ResourceManager.GetString("LanguageSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} set for {1} as main world..
        /// </summary>
        public static string MainWorldSet {
            get {
                return ResourceManager.GetString("MainWorldSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0} to &apos;{1}&apos;, I didn&apos;t found a GW2 api key for you.
        ///To get yourself wvw roles assigned please register your api key.
        ///For more information message me &quot;got#help&quot;!.
        /// </summary>
        public static string NoGw2KeyRegisteredAutoVerifyOnJoin {
            get {
                return ResourceManager.GetString("NoGw2KeyRegisteredAutoVerifyOnJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There seems to be an issue with the role &apos;{0}&apos; on &apos;{1}&apos; it&apos;s most likely above the &apos;Grey-O-Tron&apos; role making it impossible for me to assign it..
        /// </summary>
        public static string NotGuildUserRoleIssue {
            get {
                return ResourceManager.GetString("NotGuildUserRoleIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must give at least one world name separated by ; for the set-worlds command to work..
        /// </summary>
        public static string NoWorldsInCommand {
            get {
                return ResourceManager.GetString("NoWorldsInCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong whilst trying to assign you the &apos;{0}&apos; role on &apos;{1}&apos;, the bot owner is notified, please  try again in 60 minutes..
        /// </summary>
        public static string RoleAssignmentFailed {
            get {
                return ResourceManager.GetString("RoleAssignmentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong whilst trying to assign &apos;{0}&apos; the &apos;{1}&apos; role on &apos;{2}&apos;, the bot owner is notified, please try again in 60 minutes..
        /// </summary>
        public static string RoleAssignmentFailedForUser {
            get {
                return ResourceManager.GetString("RoleAssignmentFailedForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your GW2 world roles have been removed from {0}.
        ///Goodbye!.
        /// </summary>
        public static string RolesWereRemoved {
            get {
                return ResourceManager.GetString("RolesWereRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no where.
        /// </summary>
        public static string RolesWereRemovedNoWhere {
            get {
                return ResourceManager.GetString("RolesWereRemovedNoWhere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only use the {0} command on a Discord server..
        /// </summary>
        public static string ServerOnlyCommand {
            get {
                return ResourceManager.GetString("ServerOnlyCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your key has been stored, and I also tried to verify you on the following Discord servers:
        ///{0}.
        /// </summary>
        public static string SuccessfullyVerified {
            get {
                return ResourceManager.GetString("SuccessfullyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry this command is for the botowner only!.
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve your world from &apos;{0}&apos;.
        /// </summary>
        public static string UnknownWorld {
            get {
                return ResourceManager.GetString("UnknownWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; already had the role &apos;{1}&apos; on &apos;{2}&apos;, no action taken..
        /// </summary>
        public static string UserAlreadyHadRole {
            get {
                return ResourceManager.GetString("UserAlreadyHadRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} most likely changed their Discord username from {1} to {2}#{3} please ask {0} to update their key.
        ///{4}.
        /// </summary>
        public static string UserChangedDiscordUsername {
            get {
                return ResourceManager.GetString("UserChangedDiscordUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been assigned {1} on {2}.
        /// </summary>
        public static string UserHasBeenAssignedRole {
            get {
                return ResourceManager.GetString("UserHasBeenAssignedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an issue on the &apos;{0}&apos; for the role &apos;{1}&apos; an administrator from the server is notified..
        /// </summary>
        public static string UserMessageForRoleIssue {
            get {
                return ResourceManager.GetString("UserMessageForRoleIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user you are trying to verify was not found on this Discord server..
        /// </summary>
        public static string UserNotFoundForVerification {
            get {
                return ResourceManager.GetString("UserNotFoundForVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s world is not in &apos;{1}&apos; worlds list, cannot assign the role {2}.
        /// </summary>
        public static string WorldNotInDiscordServerWorlds {
            get {
                return ResourceManager.GetString("WorldNotInDiscordServerWorlds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} set for {1}.
        /// </summary>
        public static string WorldsSetForGuild {
            get {
                return ResourceManager.GetString("WorldsSetForGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you.
        /// </summary>
        public static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have the role &apos;{0}&apos; on &apos;{1}&apos;, nothing changed..
        /// </summary>
        public static string YouAlreadyHadRole {
            get {
                return ResourceManager.GetString("YouAlreadyHadRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve most likely changed your discord username from {0} to {1}#{2}, please update your key.
        ///{3}.
        /// </summary>
        public static string YouChangedDiscordUsername {
            get {
                return ResourceManager.GetString("YouChangedDiscordUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been assigned {0} on {1}.
        /// </summary>
        public static string YouHaveBeenAssignedRole {
            get {
                return ResourceManager.GetString("YouHaveBeenAssignedRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your.
        /// </summary>
        public static string Your {
            get {
                return ResourceManager.GetString("Your", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your world &apos;{0}&apos; is not in this server&apos;s &apos;{1}&apos; worlds list..
        /// </summary>
        public static string YourWorldNotInDiscordServerWorlds {
            get {
                return ResourceManager.GetString("YourWorldNotInDiscordServerWorlds", resourceCulture);
            }
        }
    }
}
